const {setup}=require('./accessibility.cjs');
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');
const t=setup('','pa.html');
const counties=vm.runInContext('COUNTIES',t.ctx),data=vm.runInContext('DATA',t.ctx);
const expected='Adams,Allegheny,Armstrong,Beaver,Bedford,Berks,Blair,Bradford,Bucks,Butler,Cambria,Cameron,Carbon,Centre,Chester,Clarion,Clearfield,Clinton,Columbia,Crawford,Cumberland,Dauphin,Delaware,Elk,Erie,Fayette,Forest,Franklin,Fulton,Greene,Huntingdon,Indiana,Jefferson,Juniata,Lackawanna,Lancaster,Lawrence,Lebanon,Lehigh,Luzerne,Lycoming,McKean,Mercer,Mifflin,Monroe,Montgomery,Montour,Northampton,Northumberland,Perry,Philadelphia,Pike,Potter,Schuylkill,Snyder,Somerset,Sullivan,Susquehanna,Tioga,Union,Venango,Warren,Washington,Wayne,Westmoreland,Wyoming,York'.split(',');
assert.deepEqual(Array.from(counties,x=>x.county),expected);
assert.equal(t.nodes['edition-state'].value,'PA');
assert.deepEqual(JSON.parse(JSON.stringify(counties)),JSON.parse(fs.readFileSync(path.join(root,'data/public/pennsylvania-county-veterans-offices.json'))));
assert.deepEqual(JSON.parse(JSON.stringify(data)),JSON.parse(fs.readFileSync(path.join(root,'data/public/pennsylvania-resources.json'))));
assert.equal(new Set(data.map(x=>x.program_id)).size,data.length);
for(const county of expected){
 t.nodes.county.value=county;t.nodes.county.events.change();
 assert(t.nodes['county-panel'].innerHTML.includes(county+' County'));
 assert(t.nodes['county-panel'].innerHTML.includes(counties.find(c=>c.county===county).phone));
 assert(t.nodes['county-panel'].innerHTML.includes('PA Link statewide routing'));
 assert(t.nodes['county-panel'].innerHTML.includes('717-783-8975'));
 assert(t.nodes.results.innerHTML.includes('resource-pa-link'));
 assert(!t.nodes.results.innerHTML.includes('resource-ohio-'));
}
for(const list of Object.values(vm.runInContext('routes',t.ctx)))for(const id of list)assert(data.some(x=>x.program_id===id),id);
assert.equal(counties.find(c=>c.county==='Beaver').phone,'724-770-4452');
assert.equal(counties.find(c=>c.county==='Potter').phone,'814-274-8290 ext. 210');
assert.equal(counties.find(c=>c.county==='Montour').phone,'570-271-3061 ext. 1600');
t.nodes.county.value='Montgomery';t.nodes.county.events.change();assert(t.nodes['county-panel'].innerHTML.includes('vacant'));
const a=setup('?county=Delaware&view=accessibility','pa.html');
assert(a.nodes['access-first'].innerHTML.includes('610-891-4646'));
assert(!a.nodes['access-first'].innerHTML.includes('740-833-2010'));
assert(a.nodes['access-first'].innerHTML.includes('PA Link'));
a.nodes['access-veteran'].value='yes';a.nodes['access-home'].value='new';a.nodes['access-home'].events.change();assert(a.nodes['access-first'].innerHTML.includes('VA adapted housing team'));
a.nodes['access-home'].value='family';a.nodes['access-home'].events.change();assert(a.nodes['access-routing'].innerHTML.includes('Temporary family home'));
a.nodes['access-veteran'].value='no';a.nodes['access-home'].value='rent';a.nodes['access-home'].events.change();assert(!a.nodes['access-routing'].innerHTML.includes('Veteran route:'));assert(a.nodes['access-routing'].innerHTML.includes('Rented home'));
a.nodes['access-home'].value='facility';a.nodes['access-home'].events.change();assert(a.nodes['access-routing'].innerHTML.includes('800-833-5196'));
a.nodes['access-waiver'].value='waiver';a.nodes['access-waiver'].events.change();assert(a.nodes['access-first'].innerHTML.includes('Your service coordinator'));
assert(!vm.runInContext('shareURL().href',a.ctx).includes('access-home'));
const seniors=setup('?county=Erie&view=seniors&topic=vision','pa.html');
assert(seniors.nodes.results.innerHTML.includes('resource-pa-bbvs'));
assert(!seniors.nodes.results.innerHTML.includes('resource-va-'));
seniors.nodes.search.value='HISA';seniors.nodes.search.events.input();assert(!seniors.nodes.results.innerHTML.includes('resource-va-hisa'));
seniors.nodes.reset.onclick();assert(!seniors.nodes['seniors-guide'].hidden);
const link=new URL(vm.runInContext('shareURL().href',seniors.ctx));assert.equal(link.pathname,'/pa.html');assert.equal(link.searchParams.get('county'),'Erie');
const unknown=setup('?county=Morrow&view=bad','pa.html');assert.equal(unknown.nodes.county.value,'');
a.nodes['edition-state'].value='OH';a.nodes['edition-state'].events.change();const toOhio=new URL(a.navigation());assert.equal(toOhio.pathname,'/index.html');assert(!toOhio.searchParams.has('county'));assert.equal(toOhio.searchParams.get('view'),'accessibility');
const ohio=setup('?county=Delaware&view=seniors');ohio.nodes['edition-state'].value='PA';ohio.nodes['edition-state'].events.change();const toPA=new URL(ohio.navigation());assert.equal(toPA.pathname,'/pa.html');assert.equal(toPA.searchParams.get('view'),'seniors');assert(!toPA.searchParams.has('county'));
const html=fs.readFileSync(path.join(root,'pa.html'),'utf8');assert(html.includes('<option value="OH">Ohio</option>'));assert(!/ohio\.gov|PASSPORT|OSHIIP|HOME Choice|AMVETS directory/.test(html));
assert(data.find(x=>x.program_id==='pa-patf').constraints.some(x=>x.includes('Repayment')));
assert(data.find(x=>x.program_id==='pa-phfa-access').constraints.some(x=>x.includes('not a general grant')));
console.log('PASS: all 67 PA county contacts, state isolation and switching, truthful statewide routing, vacancies, phone extensions, seniors, accessibility branches, shared links and PA funding limits.');
