"""Build a self-contained Ohio community bingo page from reviewed venue records."""
import json

def make_bingo(root):
    records=json.loads((root/'data/public/ohio-bingo.json').read_text())
    centers=json.loads((root/'data/public/ohio-community-centers.json').read_text())
    for center in centers:
        current=next((r for r in records if r['id']==center['id']),None)
        if current:
            sources=list({(s['url'],s['scope']):s for s in current['sources']+center['sources']}.values())
            current.update(center)
            current['sources']=sources
        else:
            records.append(center)
    authorized=json.loads((root/'data/public/ohio-bingo-authorized.json').read_text())
    known={r['license_number'] for r in records if r['license_number']}
    records += [r for r in authorized if r['license_number'] not in known]
    counties=json.loads((root/'data/public/ohio-county-veterans-offices.json').read_text())
    for r in records:
        assert r['county'] in {c['county'] for c in counties}
        assert r['category'] in ('charitable','senior','licensed','center')
    payload=json.dumps(records,ensure_ascii=True).replace('<','\\u003c')
    zip_data=(root/'data/public/us-zip-centroids.json').read_text().strip()
    options=''.join('<option>'+c['county']+'</option>' for c in counties)
    return TEMPLATE.replace('__DATA__',payload).replace('__COUNTIES__',options).replace('__ZIPDATA__',zip_data)

TEMPLATE='''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Ohio Bingo and Senior Centers | Veteran Home Guardians</title>
<meta name="description" content="Find nearby senior centers, exercise, crafts, cards, meals and bingo across Ohio. Search by ZIP code and distance.">
<link rel="canonical" href="https://travisvought-byte.github.io/vhg-veteran-resident-guide/bingo.html">
<style>
:root{--navy:#183449;--green:#335947;--paper:#f5f3ed;--line:#d9dfda}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:#20313a;font:17px/1.55 system-ui,sans-serif}header{background:var(--navy);color:white;padding:30px max(20px,calc((100vw - 1120px)/2))}header a{color:white}h1,h2{font-family:Georgia,serif}h1{font-size:clamp(28px,5vw,42px);line-height:1.2}header p{max-width:780px}main{max-width:1160px;padding:24px;margin:auto}a{color:#215b76;text-underline-offset:3px}p{margin:10px 0 16px}.notice{background:#fff8e7;border-left:4px solid #bb8e36;padding:14px 18px}.tools{display:grid;grid-template-columns:1fr 1fr 2fr;gap:16px;margin:24px 0}label{display:block;font-weight:650;font-size:14px}input,select,button{font:inherit;padding:12px;border:1px solid #abb8b1;border-radius:6px;background:white;color:inherit}input,select,textarea{width:100%}textarea{font:inherit;padding:12px;border:1px solid #abb8b1;border-radius:6px}.submission{margin-top:32px;padding:24px;background:white;border:1px solid var(--line)}button{cursor:pointer}:focus-visible{outline:3px solid #bb8e36;outline-offset:3px}.nearby-action{display:flex;align-items:end}.nearby-action button{background:var(--green);color:white;width:100%}summary{cursor:pointer}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}article{background:white;border:1px solid var(--line);border-radius:9px;padding:22px}h2{font-size:25px;color:var(--navy);margin-top:12px}.badge{display:inline-block;padding:4px 8px;background:#e8eeea;font-size:13px;border-radius:4px}.small{font-size:14px}.sources{font-size:13px;border-top:1px solid var(--line);padding-top:12px}.sources li{margin:8px 0;overflow-wrap:anywhere}.actions{display:flex;flex-wrap:wrap;gap:16px}.empty{padding:24px;background:white;grid-column:1/-1}footer{font-size:14px;margin:30px 0}.skip{position:absolute;top:-100px;left:12px;background:white;padding:12px}.skip:focus{top:12px}#count{font-weight:650}article p,article li{overflow-wrap:anywhere}@media(max-width:720px){.tools,.grid{grid-template-columns:1fr}main{padding:18px}}@media print{header{background:white;color:black;padding:0}header a{color:black}.tools,button,.report,.skip,.submission{display:none}main{padding:0}.grid{display:block}article{break-inside:avoid;margin:12px 0;padding:14px}.notice{background:white}.sources{display:block}body{background:white;font-size:12px}h1{font-size:26px}h2{font-size:20px}}
</style></head><body><a class="skip" href="#listings">Skip to listings</a>
<header><a href="index.html?view=community">← Ohio Veteran Resident Resource Guide</a><h1>Bingo &amp; Senior Centers</h1><p>Find places to connect, play, learn and stay active. Enter your ZIP code to explore nearby.</p></header>
<main><p>Explore senior centers, exercise, crafts, games and meals alongside 717 state-listed bingo entries. Schedules can change; check with the venue before traveling. <a href="#submit-details">Suggest a place or activity</a>.</p>
<form id="bingo-nearby"><div class="tools"><div><label for="bingo-zip">Your ZIP code</label><input id="bingo-zip" inputmode="numeric" autocomplete="postal-code" maxlength="5" pattern="[0-9]{5}" placeholder="e.g. 43334" aria-describedby="nearby-status"></div><div><label for="bingo-radius">Within</label><select id="bingo-radius"><option value="10">10 miles</option><option value="25">25 miles</option><option value="50" selected>50 miles</option><option value="100">100 miles</option><option value="200">200 miles</option><option value="all">Any distance</option></select></div><div class="nearby-action"><button type="submit">Find nearby activities</button></div></div></form><p id="nearby-status" class="small" role="status" aria-live="polite">Distances are approximate straight-line miles.</p>
<div class="tools"><div><label for="bingo-kind">Show</label><select id="bingo-kind"><option value="">Bingo &amp; Senior Centers</option><option value="bingo">Bingo</option><option value="centers">Senior Centers</option><option value="exercise">Exercise and movement</option><option value="crafts">Arts and crafts</option><option value="games">Cards and social games</option><option value="meals">Meals and cafés</option><option value="trips">Organized trips</option><option value="licensed">State-listed Type I bingo</option><option value="scheduled">Bingo with session times</option><option value="senior">Senior-center bingo</option></select></div><div><label for="bingo-search">Search places and activities</label><input id="bingo-search" type="search" placeholder="Place, activity, town or day…"></div><details class="county-filter"><summary>County filter (optional)</summary><label for="bingo-county">County</label><select id="bingo-county"><option value="">All Ohio counties</option>__COUNTIES__</select></details></div>
<div class="actions"><button id="bingo-reset">Clear filters</button><button id="bingo-print">Print this list</button></div><p id="count" role="status" aria-live="polite"></p><section id="listings" aria-label="Bingo and senior centers"></section><noscript><p>Enable JavaScript to search, or <a href="data/public/ohio-bingo.json">read the venue records</a> or <a href="data/public/ohio-community-centers.json">senior-center records</a>.</p></noscript>
<section id="submit-details" class="submission"><h2>Suggest a place or activity</h2><p>Know a senior center, regular activity or bingo game? Send the details to Travis.</p>
<form id="bingo-submit"><div class="tools"><div><label for="submit-venue">Venue name</label><input id="submit-venue" required maxlength="160"></div><div><label for="submit-county">County</label><input id="submit-county" maxlength="80"></div><div><label for="submit-source">Website or Facebook link (optional)</label><input id="submit-source" type="url" maxlength="500"></div></div><label for="submit-info">Activities, days, times, prices and other details</label><textarea id="submit-info" required rows="4" maxlength="2500"></textarea><label for="submit-contact">Your name or reply email (optional)</label><input id="submit-contact" maxlength="200"><p><button type="submit">Open email to Travis</button></p><p class="small">Opens a draft in your email app for you to send. You can also email <a href="mailto:travis@vethomeguard.org">travis@vethomeguard.org</a>.</p></form></section>
<footer><p>Suggest a venue or correction: <a href="mailto:travis@vethomeguard.org?subject=Ohio%20community%20activity">travis@vethomeguard.org</a>. Share public venue information only, without resident or health details.</p><p>Updated October 9, 2026. ZIP coordinates: <a href="https://www.geonames.org/">GeoNames</a> / <a href="https://github.com/midwire/free_zipcode_data">Midwire</a> (<a href="https://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a>).</p><p><a href="data/public/ohio-bingo.json">Download researched venue data</a> · <a href="data/public/ohio-bingo-authorized.json">Download statewide Type I data</a> · <a href="data/public/ohio-community-centers.json">Download senior-center data</a> · <a href="index.html">Return to benefits and support referrals</a></p></footer></main>
<script>
const BINGO=__DATA__;
const ZIP_CENTROIDS=__ZIPDATA__;
let activeZip='';
function milesBetween(a,b){const rad=x=>x*Math.PI/180;const lat=rad(b[0]-a[0]),lon=rad(b[1]-a[1]);const h=Math.sin(lat/2)**2+Math.cos(rad(a[0]))*Math.cos(rad(b[0]))*Math.sin(lon/2)**2;return 3958.7613*2*Math.atan2(Math.sqrt(h),Math.sqrt(Math.max(0,1-h)))}
function venueCoordinates(r){const zip=r.address.match(/\\bOH\\s+(\\d{5})(?:-\\d{4})?\\b/);return zip?ZIP_CENTROIDS[zip[1]]:null}
function nearbyBingo(rows,zip,radius){const origin=ZIP_CENTROIDS[zip];if(!origin)return null;return rows.flatMap(r=>{const coords=venueCoordinates(r);if(!coords)return [];const distanceMiles=milesBetween(origin,coords);return distanceMiles<=radius?[{...r,distanceMiles}]:[]}).sort((a,b)=>a.distanceMiles-b.distanceMiles||a.name.localeCompare(b.name))}

const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const safeURL=s=>{try{const u=new URL(s);return u.protocol==='https:'?u.href:''}catch{return ''}};
function filteredBingo(county,kind,q){q=q.toLowerCase().trim();return BINGO.filter(r=>(!county||r.county===county)&&(!kind||(kind==='licensed'?!!r.license_number:kind==='scheduled'?!!r.schedule:kind==='centers'?!!r.is_center:kind==='bingo'?(r.category!=='center'||r.offers_bingo):['exercise','crafts','games','meals','trips'].includes(kind)?(r.activity_tags||[]).includes(kind):r.category===kind))&&(!q||[r.name,r.address,r.schedule,r.authorized_days,r.county,...(r.activities||[])].join(' ').toLowerCase().includes(q)))}
function render(){const county=$('bingo-county').value,kind=$('bingo-kind').value,q=$('bingo-search').value,base=filteredBingo(county,kind,q),rows=activeZip?nearbyBingo(base,activeZip,$('bingo-radius').value==='all'?Infinity:Number($('bingo-radius').value)):base;$('count').textContent=rows.length+(activeZip?' venues'+($('bingo-radius').value==='all'?'':' within '+$('bingo-radius').value+' miles')+' of '+activeZip+' · closest first':' of '+BINGO.length+' venues')+(county?' in '+county+' County':'');const card=r=>{

return '<article id="'+esc(r.id)+'"><span class="badge">'+(r.is_center?'Senior center':r.schedule?'Bingo · session times listed':'Bingo · state authorization')+'</span><h2>'+esc(r.name)+'</h2>'+(Number.isFinite(r.distanceMiles)?'<p class="badge">About '+r.distanceMiles.toFixed(1)+' miles away</p>':'')+'<p>'+esc(r.address)+'<br><strong>'+esc(r.county)+' County</strong></p>'+(r.opening_hours?'<p><strong>Center hours:</strong> '+esc(r.opening_hours)+'</p>':'')+(r.activities?.length?'<ul>'+r.activities.map(a=>'<li>'+esc(a)+'</li>').join('')+'</ul>':'')+(r.participation?'<p class="small">'+esc(r.participation)+'</p>':'')+(r.schedule?'<p><strong>'+ (r.is_center?'Bingo:':'When:')+'</strong> '+esc(r.schedule)+'</p>':r.authorized_days?'<p><strong>State-listed days:</strong> '+esc(r.authorized_days)+'</p>':'')+(r.cost?'<p><strong>'+(r.is_center&&r.category==='senior'?'Bingo price:':'Price:')+'</strong> '+esc(r.cost)+'</p>':'')+'<div class="actions">'+(r.phone?'<a href="tel:'+r.phone.replace(/[^0-9]/g,'')+'">'+esc(r.phone)+'</a>':'')+(safeURL(r.program_url||r.official_url)?'<a href="'+esc(safeURL(r.program_url||r.official_url))+'" target="_blank" rel="noopener noreferrer">Programs and website ↗</a>':'')+'<a class="report" href="#submit-details" data-submit="'+esc(r.id)+'">Add or update details</a></div><details class="sources"><summary>Sources and details · '+esc(r.reviewed_on)+'</summary>'+(r.license_number?'<p>Type I license '+esc(r.license_number)+'</p>':'')+r.notes.map(n=>'<p>'+esc(n)+'</p>').join('')+'<ul>'+r.sources.map(s=>'<li><a href="'+esc(safeURL(s.url))+'" target="_blank" rel="noopener noreferrer">'+esc(s.scope)+'</a></li>').join('')+'</ul></details></article>' };const groups=kind==='bingo'?[['Bingo',rows]]:[['Senior Centers',rows.filter(r=>r.is_center)],['Bingo',rows.filter(r=>!r.is_center)]];$('listings').innerHTML=groups.filter(([,items])=>items.length).map(([title,items])=>'<section aria-label="'+title+'"><h2>'+title+' ('+items.length+')</h2>'+(title==='Senior Centers'?'<p class="small">Find more centers: <a href="https://ohioasc.org/" target="_blank" rel="noopener noreferrer">Ohio Association of Senior Centers locator ↗</a></p>':'')+'<div class="grid">'+items.map(card).join('')+'</div></section>').join('')||'<p class="empty">No places match these filters. Try a larger distance or clear filters.</p>';const u=new URL(location.href);u.search='';if(county)u.searchParams.set('county',county);if(kind)u.searchParams.set('kind',kind);if(q)u.searchParams.set('q',q);if(activeZip){u.searchParams.set('zip',activeZip);u.searchParams.set('radius',$('bingo-radius').value)}history.replaceState(null,'',u)}
function applyNearby(){const zip=$('bingo-zip').value.trim();if(!zip){activeZip='';$('nearby-status').textContent='Distances are approximate straight-line miles.';render();return}if(!/^[0-9]{5}$/.test(zip)||!ZIP_CENTROIDS[zip]){activeZip='';$('nearby-status').textContent='Enter a valid five-digit US ZIP code.';render();return}activeZip=zip;$('nearby-status').textContent='Distances are approximate straight-line miles.';render()}
$('bingo-nearby').onsubmit=e=>{e.preventDefault();applyNearby()};$('bingo-radius').addEventListener('change',()=>{if(activeZip)render()});
function submissionEmail(venue,county,info,source,contact){const u=new URL('mailto:travis@vethomeguard.org');u.searchParams.set('subject','Community activity details: '+venue);u.searchParams.set('body',['Venue: '+venue,'County: '+county,'Details: '+info,'Source: '+source,'Submitted by: '+contact].join('\\n'));return u.href.replaceAll('+','%20')}
$('listings').onclick=e=>{const link=e.target.closest('[data-submit]');if(!link)return;const r=BINGO.find(r=>r.id===link.dataset.submit);if(!r)return;$('submit-venue').value=r.name;$('submit-county').value=r.county;};
$('bingo-submit').onsubmit=e=>{e.preventDefault();location.href=submissionEmail(...['submit-venue','submit-county','submit-info','submit-source','submit-contact'].map(id=>$(id).value.trim()))};
const params=new URLSearchParams(location.search);if([...$('bingo-county').options].some(o=>o.value===params.get('county')))$('bingo-county').value=params.get('county');if(['licensed','scheduled','senior','centers','exercise','crafts','games','meals','trips','bingo'].includes(params.get('kind')))$('bingo-kind').value=params.get('kind');$('bingo-search').value=params.get('q')||'';$('bingo-zip').value=params.get('zip')||'';$('bingo-radius').value=['10','25','50','100','200','all'].includes(params.get('radius'))?params.get('radius'):'50';if(/^[0-9]{5}$/.test($('bingo-zip').value)&&ZIP_CENTROIDS[$('bingo-zip').value])activeZip=$('bingo-zip').value;
['bingo-county','bingo-kind'].forEach(id=>$(id).addEventListener('change',render));$('bingo-search').addEventListener('input',render);$('bingo-reset').onclick=()=>{['bingo-county','bingo-kind','bingo-search','bingo-zip'].forEach(id=>$(id).value='');activeZip='';$('bingo-radius').value='50';$('nearby-status').textContent='Distances are approximate straight-line miles.';render()};$('bingo-print').onclick=()=>window.print();render();
</script></body></html>'''
