"""Build a self-contained Ohio community bingo page from reviewed venue records."""
import json

def make_bingo(root):
    records=json.loads((root/'data/public/ohio-bingo.json').read_text())
    counties=json.loads((root/'data/public/ohio-county-veterans-offices.json').read_text())
    for r in records:
        assert r['county'] in {c['county'] for c in counties}
        assert r['category'] in ('charitable','senior')
    payload=json.dumps(records,ensure_ascii=True).replace('<','\\u003c')
    options=''.join('<option>'+c['county']+'</option>' for c in counties)
    return TEMPLATE.replace('__DATA__',payload).replace('__COUNTIES__',options)

TEMPLATE='''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Ohio Bingo and Community Activities | Veteran Home Guardians</title>
<meta name="description" content="Find local charitable bingo and senior-center bingo, with schedules, sources and details to confirm before attending. Initial four-county Ohio coverage.">
<link rel="canonical" href="https://travisvought-byte.github.io/vhg-veteran-resident-guide/bingo.html">
<style>
:root{--navy:#183449;--green:#335947;--paper:#f5f3ed;--line:#d9dfda}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:#20313a;font:17px/1.55 system-ui,sans-serif}header{background:var(--navy);color:white;padding:30px max(20px,calc((100vw - 1120px)/2))}header a{color:white}h1,h2{font-family:Georgia,serif}h1{font-size:clamp(28px,5vw,42px);line-height:1.2}header p{max-width:780px}main{max-width:1160px;padding:24px;margin:auto}a{color:#215b76;text-underline-offset:3px}p{margin:10px 0 16px}.notice{background:#fff8e7;border-left:4px solid #bb8e36;padding:14px 18px}.tools{display:grid;grid-template-columns:1fr 1fr 2fr;gap:16px;margin:24px 0}label{display:block;font-weight:650;font-size:14px}input,select,button{font:inherit;padding:12px;border:1px solid #abb8b1;border-radius:6px;background:white;color:inherit}input,select{width:100%}button{cursor:pointer}:focus-visible{outline:3px solid #bb8e36;outline-offset:3px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}article{background:white;border:1px solid var(--line);border-radius:9px;padding:22px}h2{font-size:25px;color:var(--navy);margin-top:12px}.badge{display:inline-block;padding:4px 8px;background:#e8eeea;font-size:13px;border-radius:4px}.small{font-size:14px}.sources{font-size:13px;border-top:1px solid var(--line);padding-top:12px}.sources li{margin:8px 0;overflow-wrap:anywhere}.actions{display:flex;flex-wrap:wrap;gap:16px}.empty{padding:24px;background:white;grid-column:1/-1}footer{font-size:14px;margin:30px 0}.skip{position:absolute;top:-100px;left:12px;background:white;padding:12px}.skip:focus{top:12px}#count{font-weight:650}article p,article li{overflow-wrap:anywhere}@media(max-width:720px){.tools,.grid{grid-template-columns:1fr}main{padding:18px}}@media print{header{background:white;color:black;padding:0}header a{color:black}.tools,button,.report,.skip{display:none}main{padding:0}.grid{display:block}article{break-inside:avoid;margin:12px 0;padding:14px}.notice{background:white}.sources{display:block}body{background:white;font-size:12px}h1{font-size:26px}h2{font-size:20px}}
</style></head><body><a class="skip" href="#listings">Skip to bingo listings</a>
<header><a href="index.html?view=community">← Ohio Veteran Resident Resource Guide</a><h1>Bingo and community activities</h1><p>Places to connect, enjoy a game and ask about a group outing. Find charitable bingo sessions and senior-center activities separately. Military service is not required; each venue has its own attendance rules.</p></header>
<main><section class="notice" aria-label="Coverage"><strong>Initial coverage: Morrow, Knox, Delaware and Marion</strong><p>Six researched venues, not a complete statewide directory. Cardington and Marengo bingo activity is confirmed firsthand by Travis Vought; that does not confirm current times, prices, accessibility or licenses.</p><p>Statewide license import is pending. The Attorney General report was visible through indexed retrieval, but direct downloads were blocked on October 8, 2026. No statewide venue count or license status is asserted here.</p></section>
<section aria-labelledby="plan"><h2 id="plan">Before planning an outing</h2><p>Confirm the next session, total cost, age and guest rules, step-free access, accessible restrooms, parking, companion attendance and any registration requirements. Accessibility has not yet been verified for these venues.</p></section>
<div class="tools"><div><label for="bingo-county">County</label><select id="bingo-county"><option value="">All Ohio counties</option>__COUNTIES__</select></div><div><label for="bingo-kind">Activity</label><select id="bingo-kind"><option value="">All listed activities</option><option value="charitable">Charitable bingo sessions</option><option value="senior">Senior-center bingo</option></select></div><div><label for="bingo-search">Search venues</label><input id="bingo-search" type="search" placeholder="Venue, town or day…"></div></div>
<div class="actions"><button id="bingo-reset">Clear filters</button><button id="bingo-print">Print this list</button></div><p id="count" role="status" aria-live="polite"></p><section id="listings" class="grid" aria-label="Bingo venues"></section><noscript><p>Enable JavaScript to search, or <a href="data/public/ohio-bingo.json">read the venue records</a>.</p></noscript>
<section class="notice"><h2>Growing across Ohio</h2><p>The license report can identify traditional bingo locations. Type I is traditional bingo; Type II covers instant gaming at bingo sessions; Type III covers instant gaming outside sessions. Pull-tab or electronic gaming locations alone are not evidence of a scheduled traditional bingo event. Senior-center activities are tracked separately; their license requirements have not been assessed here.</p><p><a href="https://charitable.ohioago.gov/Charitable-Bingo/View-Authorized-Bingo-Locations" target="_blank" rel="noopener noreferrer">Ohio Attorney General authorized locations report</a> · <a href="https://codes.ohio.gov/ohio-administrative-code/rule-109:1-4-08" target="_blank" rel="noopener noreferrer">Official license type definitions</a></p></section>
<footer><p>Suggest a venue or correction: <a href="mailto:travis@vethomeguard.org?subject=Ohio%20bingo%20listing">travis@vethomeguard.org</a>. Share public venue information only, without resident or health details.</p><p>Listings do not imply sponsorship, endorsement or partnership with VHG. Updated October 8, 2026. Sources and limits appear on every card.</p><p><a href="data/public/ohio-bingo.json">Download venue data</a> · <a href="index.html">Return to benefits and support referrals</a></p></footer></main>
<script>
const BINGO=__DATA__;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const safeURL=s=>{try{const u=new URL(s);return u.protocol==='https:'?u.href:''}catch{return ''}};
function filteredBingo(county,kind,q){q=q.toLowerCase().trim();return BINGO.filter(r=>(!county||r.county===county)&&(!kind||r.category===kind)&&(!q||[r.name,r.address,r.schedule,r.county].join(' ').toLowerCase().includes(q)))}
function render(){const county=$('bingo-county').value,kind=$('bingo-kind').value,q=$('bingo-search').value,rows=filteredBingo(county,kind,q);$('count').textContent=rows.length+' of '+BINGO.length+' venues'+(county?' in '+county+' County':'');$('listings').innerHTML=rows.map(r=>{
const report=new URL('mailto:travis@vethomeguard.org');report.searchParams.set('subject','Ohio bingo correction: '+r.id);report.searchParams.set('body','Venue: '+r.name+'\\nCounty: '+r.county+'\\nCorrection and public source:\\n\\nDo not include resident names or health details.');
return '<article id="'+esc(r.id)+'"><span class="badge">'+(r.category==='senior'?'Senior-center activity':'Charitable bingo session')+'</span><h2>'+esc(r.name)+'</h2><p>'+esc(r.address)+'<br><strong>'+esc(r.county)+' County</strong></p>'+(r.firsthand_confirmation?'<p class="badge">Bingo activity confirmed firsthand by Travis Vought</p>':'')+'<p><strong>Schedule:</strong> '+esc(r.schedule||'Current session times need confirmation.')+'</p><p><strong>Cost:</strong> '+esc(r.cost||'Ask the organizer for current prices.')+'</p><p><strong>Attendance:</strong> '+esc(r.admission)+'</p><p class="small"><strong>Accessibility:</strong> Not yet verified. Ask about your needs before visiting.</p><p class="small"><strong>License:</strong> '+esc(r.license_status)+'</p>'+r.notes.map(n=>'<p class="notice small">'+esc(n)+'</p>').join('')+'<div class="actions">'+(r.phone?'<a href="tel:'+r.phone.replace(/[^0-9]/g,'')+'">'+esc(r.phone)+(r.id==='northmor-music-bingo'?' (venue)':'')+'</a>':'')+(safeURL(r.official_url)?'<a href="'+esc(safeURL(r.official_url))+'" target="_blank" rel="noopener noreferrer">Organizer information ↗</a>':'')+'</div><div class="sources"><strong>Sources reviewed '+esc(r.reviewed_on)+'</strong><ul>'+r.sources.map(s=>'<li><a href="'+esc(safeURL(s.url))+'" target="_blank" rel="noopener noreferrer">'+esc(s.scope)+'</a></li>').join('')+'</ul>'+(r.firsthand_confirmation?'<p>'+esc(r.firsthand_confirmation.scope)+'</p>':'')+'</div><a class="report small" href="'+esc(report.href)+'">Report a problem</a></article>'}).join('')||'<p class="empty">No researched venues in this view yet. This does not mean there is no bingo in this county. Clear filters or suggest a venue.</p>';const u=new URL(location.href);u.search='';if(county)u.searchParams.set('county',county);if(kind)u.searchParams.set('kind',kind);if(q)u.searchParams.set('q',q);history.replaceState(null,'',u)}
const params=new URLSearchParams(location.search);if([...$('bingo-county').options].some(o=>o.value===params.get('county')))$('bingo-county').value=params.get('county');if(['charitable','senior'].includes(params.get('kind')))$('bingo-kind').value=params.get('kind');$('bingo-search').value=params.get('q')||'';
['bingo-county','bingo-kind'].forEach(id=>$(id).addEventListener('change',render));$('bingo-search').addEventListener('input',render);$('bingo-reset').onclick=()=>{['bingo-county','bingo-kind','bingo-search'].forEach(id=>$(id).value='');render()};$('bingo-print').onclick=()=>window.print();render();
</script></body></html>'''
